import { NetworkType, type Network } from "./network";

export const NETWORK_DEXES = {
    [NetworkType.Ethereum]: {
        "Balancer V3 (Ethereum)": "balancer-v3-ethereum",
        "Deltaswap (Ethereum)": "deltaswap-ethereum",
        "Fluid (Ethereum)": "fluid-ethereum",
        "Maverick V2 (Ethereum)": "maverick-v2-eth",
        "Ring Exchange (Ethereum)": "ring-exchange-ethereum",
        Ethervista: "ethervista",
        "Uniswap V4 (Ethereum)": "uniswap-v4-ethereum",
        "Xchange (Ethereum)": "x7-finance-ethereum",
        Blueprint: "blueprint",
        "Convergence Finance V2": "convergence-finance-v2",
        "Orion (Ethereum)": "orion-ethereum",
        "VVS V3 (Ethereum)": "vvs-v3-ethereum",
        "9inch (Ethereum)": "9inch-ethereum",
        BitSwap: "bitswap",
        "JustMoney (Ethereum)": "justmoney-ethereum",
        "Lif3 (Ethereum)": "lif3-ethereum",
        "WAGMI (Ethereum)": "wagmi-ethereum",
        Pepedex: "pepedex",
        "Solidly V3": "solidly-v3",
        "SushiSwap V3 (Ethereum)": "sushiswap-v3-ethereum",
        "LFJ V2.1 (Ethereum)": "traderjoe-v2-1-ethereum",
        "x7 Finance": "x7-finance",
        "Saitaswap (Ethereum)": "saitaswap-ethereum",
        Sashimiswap: "sashimiswap",
        "SmarDex (Ethereum)": "smardex-ethereum",
        Whiteswap: "whiteswap",
        "Antfarm (Ethereum)": "antfarm-ethereum",
        "Balancer V2 (Ethereum)": "balancer_ethereum",
        "Pancakeswap V3 (Ethereum)": "pancakeswap-v3-ethereum",
        Solidly: "solidlydex",
        "Kyberswap Classic (Ethereum)": "kyberswap_classic_ethereum",
        "Pancakeswap (Ethereum)": "pancakeswap_ethereum",
        "SafemoonSwap (Ethereum)": "safemoonswap_ethereum",
        "Spice Trade (Ethereum)": "spice_trade_ethereum",
        Unicly: "unicly",
        Verse: "verse",
        Curve: "curve",
        "Defi Swap": "defi_swap",
        "DOOAR (Ethereum)": "dooar_ethereum",
        "Fraxswap (Ethereum)": "fraxswap_ethereum",
        SakeSwap: "sakeswap",
        "Elk Finance (Ethereum)": "elk_finance_ethereum",
        "KyberSwap Elastic": "kyberswap_elastic",
        "RadioShack (Ethereum)": "radioshack_ethereum",
        "Standard (Ethereum)": "standard_ethereum",
        "Swapr (Ethereum)": "swapr_ethereum",
        Shibaswap: "shibaswap",
        SushiSwap: "sushiswap",
        "Uniswap V2": "uniswap_v2",
        "Uniswap V3": "uniswap_v3",
    },

    [NetworkType["BNB Chain"]]: {
        "Four.meme": "four-meme",
        "Omni Exchange V3 (BSC)": "omni-exchange-v3-bsc",
        "Pancakeswap Infinity (CLMM)": "pancakeswap-infinity-clmm",
        "THENA V3": "thena-v3",
        "Maverick V2 (BSC)": "maverick-v2-bsc",
        "SquadSwap Dynamo (BSC)": "squadswap-v2-bsc",
        "SquadSwap WOW (BSC)": "squadswap-v3-bsc",
        TidalDex: "tidaldex",
        TikTokFun: "tiktokfun",
        "Uniswap V4 (BSC)": "uniswap-v4-bsc",
        CoinSwap: "coinswap",
        "Curve (BSC)": "curve-bsc",
        "Unchain X": "unchain-x",
        HonorSwap: "honorswap",
        "Lif3 V3 (BSC)": "lif3-v3-bsc",
        "Orion (BSC)": "orion-bsc",
        "Pancakeswap V1 (BSC)": "pancakeswap-v1-bsc",
        "Uniswap V2 (BSC)": "uniswap-v2-bsc",
        "Biswap V3": "biswap-v3-1",
        MelegaSwap: "melegaswap",
        "Sushiswap V3 (BSC)": "sushiswap-v3-bsc",
        "THENA FUSION": "thena-fusion",
        Definix: "definix",
        DinosaurEggs: "dinosaureggs",
        "Pancakeswap (Stable)": "pancakeswap_stableswap",
        "Pancakeswap V3 (BSC)": "pancakeswap-v3-bsc",
        THENA: "thena",
        "Uniswap V3 (BSC)": "uniswap-bsc",
        W3Swap: "w3swap",
        "Nomiswap (Stable)": "nomiswap_stable",
        BabyDogeSwap: "babydogeswap",
        "DOOAR (BSC)": "dooar_bsc",
        "Fraxswap (BSC)": "fraxswap_bsc",
        Fstswap: "fstswap",
        SWYCH: "swych",
        BakerySwap: "bakeryswap",
        Nomiswap: "nomiswap",
        "SafeMoon Swap": "safemoon_swap",
        "Winery Swap": "winery_swap",
        "AutoShark Finance": "autoshark_finance",
        "Impossible Finance v3": "impossible_finance_v3",
        KnightSwap: "knightswap",
        "Wault Finance": "wault_finance",
        BabySwap: "babyswap",
        "Impossible Finance v2": "impossible_finance",
        "Sushiswap (BSC)": "sushiswap_bsc",
        "ApeSwap (BSC)": "apeswap_bsc",
        "Biswap V2": "biswap",
        "MDEX (BSC)": "mdex_bsc",
        "Pancakeswap V2 (BSC)": "pancakeswap_v2",
    },

    [NetworkType.Arbitrum]: {
        "SushiSwap (Arbitrum)": "sushiswap_arbitrum",
        "Uniswap V3 (Arbitrum)": "uniswap_v3_arbitrum",
        "Swapr (Arbitrum)": "swapr_arbitrum",
        "Curve (Arbitrum)": "curve_arbitrum",
        "Kyberswap Elastic (Arbitrum)": "kyberswap_elastic_arbitrum",
        "Kyberswap Classic (Arbitrum)": "kyberswap_classic_arbitrum",
        "Elk Finance (Arbitrum)": "elk_finance_arbitrum",
        Camelot: "camelot",
        "3xcalibur": "3xcalibur",
        SwapFish: "swapfish",
        "Arbswap (Arbitrum One)": "arbswap_arbitrum_one",
        OreoSwap: "oreoswap",
        "Balancer V2 (Arbitrum)": "balancer_arbitrum",
        Magicswap: "magicswap",
        Zyberswap: "zyberswap",
        SolidLizard: "solidlizard",
        SharkySwap: "sharkyswap",
        AlienFi: "alienfi",
        Sterling: "sterling",
        "Archly (Arbitrum)": "archly-arbitrum",
        Arbidex: "arbidex",
        "Apeswap (Arbitrum)": "apeswap-arbitrum",
        "MM Finance V3 (Arbitrum)": "mm-finance-v3-arbitrum",
        Ramses: "ramses",
        Auragi: "auragi",
        Aegis: "aegis",
        "Camelot V3": "camelot-v3",
        "LFJ V2.1 (Arbitrum)": "traderjoe-v2-1-arbitrum",
        Chronos: "chronos",
        "LFGswap (Arbitrum)": "lfgswap-arbitrum",
        Swaprum: "swaprum",
        "Solunea (Arbitrum)": "solunea-arbitrum",
        "Ramses V2": "ramses-v2",
        "Sushiswap V3 (Arbitrum)": "sushiswap-v3-arbitrum",
        SpartaDEX: "spartadex",
        "Pancakeswap V2 (Arbitrum)": "pancakeswap-v2-arbitrum",
        "Pancakeswap V3 (Arbitrum)": "pancakeswap-v3-arbitrum",
        "SmarDex (Arbitrum)": "smardex-arbitrum",
        "Pancakeswap Stableswap (Arbitrum)": "pancakeswap-stableswap-arbitrum",
        "Solidly V3 (Arbitrum)": "solidly-v3-arbitrum",
        "LFJ V2.2 (Arbitrum)": "traderjoe-v2-2-arbitrum",
        "Moonbase Alpha": "moonbase-alpha",
        "Deltaswap (Arbitrum)": "deltaswap",
        "Uniswap V2 (Arbitrum)": "uniswap-v2-arbitrum",
        "Uniswap V4 (Arbitrum)": "uniswap-v4-arbitrum",
        "Maverick V2 (Arbitrum)": "maverick-v2-arbitrum",
        "Balancer V3 (Arbitrum)": "balancer-v3-arbitrum",
        "Fluid (Arbitrum)": "fluid-arbitrum",
    },

    [NetworkType["Polygon POS"]]: {
        Quickswap: "quickswap",
        "Sushiswap (Polygon POS)": "sushiswap_polygon_pos",
        "ApeSwap (Polygon)": "apeswap_polygon",
        Dinoswap: "dinoswap",
        "Firebird Finance (Polygon)": "firebird_finance_polygon",
        ComethSwap: "comethswap",
        Dfyn: "dfyn",
        "Elk Finance (Polygon)": "elk_finance_polygon",
        "Wault Finance (Polygon)": "wault_finance_polygon",
        "Jetswap (Polygon)": "jetswap_polygon",
        PolyDEX: "polydex",
        "Gravity Finance": "gravity_finance",
        "Polycat Finance": "polycat_finance",
        "Algebra Finance": "algebra_finance",
        "Uniswap V3 (Polygon POS)": "uniswap_v3_polygon_pos",
        NachoSwap: "nachoswap",
        "Greenhouse DEX": "greenhouse_dex",
        "JustMoney (Polygon POS)": "justmoney_polygon_pos",
        "RadioShack (Polygon POS)": "radioshack_polygon_pos",
        Dystopia: "dystopia",
        VulcanDex: "vulcandex",
        "Kyberswap Classic (Polygon)": "kyberswap_classic_polygon",
        AuraSwap: "auraswap",
        "Fraxswap (Polygon POS)": "fraxswap_polygon_pos",
        "Curve (Polygon POS)": "curve_polygon_pos",
        "Honeyswap (Polygon)": "honeyswap_polygon",
        MeshSwap: "meshswap",
        "MM Finance (Polygon)": "mm-finance-polygon",
        "Spice Trade (Polygon)": "spice_trade_polygon",
        "Kyberswap Elastic (Polygon)": "kyberswap_elastic_polygon",
        "Quickswap (v3)": "quickswap_v3",
        "Balancer V2 (Polygon)": "balancer_polygon",
        "lif3 (Polygon)": "lif3-polygon",
        "CrowdSwap (Polygon)": "crowdswap-polygon",
        "Satin Exchange": "satin-exchange",
        "Phenix Finance (Polygon)": "phenix-finance-polygon",
        "Sushiswap V3 (Polygon)": "sushiswap-v3-polygon",
        "PearlFi V1": "pearl-exchange",
        Retro: "retro",
        "PearlFi V1.5": "pearlfi-v1-5",
        "SmarDex (Polygon)": "smardex-polygon",
        "Archly (Polygon)": "archly-polygon",
        "IX Swap": "ix-swap",
        "Lif3 V3 (Polygon)": "lif3-v3-polygon",
        "DOOAR (Polygon)": "dooar-polygon",
        "Uniswap V2 (Polygon)": "uniswap-v2-polygon",
        "Uniswap V4 (Polygon)": "uniswap-v4-polygon",
        GT3: "gt3",
        "W-DEX (Polygon)": "w-dex-polygon",
        "Fluid (Polygon)": "fluid-polygon",
    },

    [NetworkType.opBNB]: {
        BinarySwap: "binaryswap",
        Luigiswap: "luigiswap",
        Fourdex: "fourdex",
        Knightdex: "knightdex",
        "PixelSwap (opBNB)": "pixelswap-opbnb",
        MobyDEX: "mobydEX",
        "RocketSwap (opBNB)": "rocketswap-opbnb",
        OpbnbSwap: "opbnbswap",
        CUBISwap: "cubiswap",
        "AllInXSwap (opBnb)": "allinxswap-opbnb",
        "Pancakeswap V2 (opBnb)": "pancakeswap-v2-opbnb",
        "Pancakeswap V3 (opBnb)": "pancakeswap-v3-opbnb",
        "DerpDex (opBnb)": "derpdex-opbnb",
        "Dex on Crypto (opBnb)": "dex-on-crypto-opbnb",
        "Thena (opBnb)": "thena-opbnb",
        uDEX: "udex",
    },

    [NetworkType.ZkSync]: {
        "Koi Finance": "mute",
        "SpaceFi (ZkSync)": "spacefi_zksync",
        GemSwap: "gemswap",
        SyncSwap: "syncswap",
        Velocore: "velocore",
        "WAGMI (zkSync)": "wagmi-zksync",
        "MERLIN DEX": "merlin-dex",
        "Onsen Swap": "onsen-swap",
        Solunea: "solunea",
        veSync: "vesync",
        Starmaker: "starmaker",
        eZKalibur: "ezkalibur",
        zkSwap: "zkswap-finance",
        "DerpDEX (zkSync)": "derpdex",
        "Pancakeswap V3 (zkSync)": "pancakeswap-v3-zksync",
        "Pancakeswap V2 (zkSync)": "pancakeswap-v2-zksync",
        "Dracula Finance": "dracula-finance",
        "iZiSwap (zkSync)": "iziswap-zksync",
        "iZiSwap V2 (zkSync)": "iziswap-v2-zksync",
        "Pixelswap (zkSync)": "pixelswap-zksync",
        "Uniswap V3 (zkSync)": "uniswap-v3-zksync",
        "Velocore V2 (ZkSync)": "velocore-v2-zksync",
        "SyncSwap V2": "syncswap-v2-zksync",
        "Archly (zkSync)": "archly-zksync",
        "SyncSwap V2.1 (zkSync)": "syncswap-v2-1-zksync",
        "Koi Finance V3": "koi-finance-v3",
        "zkSwap Finance V3": "zkswap-v3",
        "zkSwap Finance StableSwap": "zkswap-finance-stableswap",
        Holdstation: "holdstation",
        "SyncSwap V3 (ZkSync)": "syncswap-v3-zksync",
        "Maverick V2 (zkSync)": "maverick-v2-zksync",
    },

    [NetworkType.Base]: {
        Rocketswap: "rocketswap",
        "Aerodrome Slipstream 2": "aerodrome-slipstream-2",
        "Fluid (Base)": "fluid-base",
        "Mint Club (Base)": "mint-club-base",
        Thirdfy: "thirdfy",
        "Virtuals Unicorn (Base)": "virtuals-unicorn-base",
        "Balancer V3 (Base)": "balancer-v3-base",
        "Omni Exchange V2 (Base)": "omni-exchange-v2-base",
        "Omni Exchange V3 (Base)": "omni-exchange-v3-base",
        "Pancakeswap Infinity (CLMM) (Base)": "pancakeswap-infinity-clmm-base",
        "Quickswap V2 (Base)": "quickswap-v2-base",
        "Quickswap V4 (Base)": "quickswap-v4-base",
        "Deltaswap (Base)": "deltaswap-base",
        "Hydrex Integral": "hydrex-integral",
        "Rubicon (Base)": "rubicon-base",
        "Treble V4": "treble-v4",
        "9mm V3 (Base)": "9mm-v3-base",
        "Maverick V2 (Base)": "maverick-v2-base",
        "Virtuals (Base)": "virtuals-base",
        "Alien Base V3": "alien-base-v3",
        "Kim V4 (Base)": "kim-v4-base",
        "SquadSwap (Base)": "squadswap-base",
        "Treble V2": "treble-v2",
        "Uniswap V4 (Base)": "uniswap-v4-base",
        "Aerodrome SlipStream": "aerodrome-slipstream",
        "BaseSwap V3": "baseswap-v3",
        BunnySwap: "bunnyswap",
        "Curve (Base)": "curve-base",
        Infusion: "infusion",
        "SwapBased V3": "swapbased-v3",
        "Synthswap V3": "synthswap-v3",
        CitadelSwap: "citadelswap",
        "SharkSwap (Base)": "sharkswap-base",
        "Solidly V3 (Base)": "solidly-v3-base",
        "Uniswap V2 (Base)": "uniswap-v2-base",
        "Aerodrome (Base)": "aerodrome-base",
        "DackieSwap V2 (Base)": "dackieswap-v2-base",
        "Equalizer (Base)": "equalizer-base",
        "iZiSwap (Base)": "iziswap-base",
        "SushiSwap V2 (Base)": "sushiswap-v2-base",
        "Alien Base": "alien-base",
        "DackieSwap V3 (Base)": "dackieswap-v3-base",
        "Pancakeswap V2 (Base)": "pancakeswap-v2-base",
        "Pancakeswap V3 (Base)": "pancakeswap-v3-base",
        "Uniswap V3 (Base)": "uniswap-v3-base",
        "Balancer V2 (Base)": "balancer-v2-base",
        BaseSwap: "baseswap",
        "Sushiswap V3 (Base)": "sushiswap-v3-base",
        SwapBased: "swapbased",
        "Swapline (Base)": "swapline-base",
    },

    [NetworkType.Mantle]: {
        "FusionX V3": "fusionx-v3",
        "Crust Finance V2": "crust-finance-v2",
        "funny.money": "funny-money",
        "Merchant Moe Liquidity Book (Mantle)": "merchant-moe-liquidity-book-mantle",
        Methlab: "methlab",
        TropicalSwap: "tropicalswap",
        "Archly (Mantle)": "archly-mantle",
        "Butter.xyz": "butter-xyz",
        "Cleopatra Exchange": "cleopatra-exchange",
        "Merchant Moe (Mantle)": "merchant-moe-mantle",
        "Stratum Exchange": "stratum-exchange",
        "Crust Finance": "crust-finance",
        "iZiSwap (Mantle)": "iziswap-mantle",
        "Swapsicle V2 (Mantle)": "swapsicle-v2-mantle",
        "Velocimeter (Mantle)": "velocimeter-mantle",
        "Agni Finance": "agni-finance",
        "FusionX V2": "fusionx-v2",
    },

    [NetworkType.Optimism]: {
        ZipSwap: "zipswap",
        "Balancer V3 (Optimism)": "balancer-v3-optimism",
        "Omni Exchange V2 (Optimism)": "omni-exchange-v2-optimism",
        "Omni Exchange V3 (Optimism)": "omni-exchange-v3-optimism",
        "Rubicon (Optimism)": "rubicon-optimism",
        "Uniswap V4 (Optimism)": "uniswap-v4-optimism",
        "Solidly V3 (Optimism)": "solidly-v3-optimism",
        "SquadSwap V2 (Optimism)": "squadswap-v2-optimism",
        "SquadSwap V3 (Optimism)": "squadswap-v3-optimism",
        SuperSwap: "superswap",
        "SushiSwap V2 (Optimism)": "sushiswap-v2-optimism",
        "Velodrome Finance SlipStream": "velodrome-finance-slipstream",
        "DackieSwap V2 (Optimism)": "dackieswap-v2-optimism",
        "DackieSwap V3 (Optimism)": "dackieswap-v3-optimism",
        OpenXSwap: "openxswap",
        "Sushiswap V3 (Optimism)": "sushiswap-v3-optimism",
        "Swapline (Optimism)": "swapline-optimism",
        "Uniswap V2 (Optimism)": "uniswap-v2-optimism",
        "Velodrome Finance v2": "velodrome-finance-v2",
        "Archly (Optimism)": "archly-optimism",
        "Beethoven X (Optimism)": "beethoven_x_optimism",
        "Elk Finance (Optimism)": "elk_finance_optimism",
        "Fraxswap (Optimism)": "fraxswap_optimism",
        "Kyberswap Classic (Optimism)": "kyberswap_classic_optimism",
        "Kyberswap Elastic (Optimism)": "kyberswap_elastic_optimism",
        "Curve (Optimism)": "curve_optimism",
        "Radioshack (Optimism)": "radioshack_optimism",
        "Uniswap V3 (Optimism)": "uniswap_v3_optimism",
        "Velodrome Finance": "velodrome",
    },

    [NetworkType.Avalanche]: {
        HakuSwap: "hakuswap",
        "Sushiswap (Avalanche)": "sushiswap_avalanche",
        Thorus: "thorus",
        YetiSwap: "yetiswap",
        "Lydia Finance": "lydia_finance",
        Pangolin: "pangolin",
        LFJ: "traderjoe",
        "Balancer V3 (Avalanche)": "balancer-v3-avalanche",
        "Pharaoh Exchange Legacy": "pharaoh-exchange-legacy",
        "Pharaoh Exchange V3": "pharaoh-exchange-v3",
        AquaSpace: "aquaspace",
        "Arena DEX": "arena-dex",
        "Blackhole V2": "blackhole-v2",
        "Blackhole V3": "blackhole-v3",
        "Omni Exchange V2 (Avalanche)": "omni-exchange-v2-avalanche",
        "Pangolin V3": "pangolin-v3",
        FWX: "fwx",
        "PyreSwap (Avalanche)": "pyreswap-avalanche",
        "LFJ V2.2 (Avalanche)": "traderjoe-v2-2-avalanche",
        "Uniswap V4 (Avalanche)": "uniswap-v4-avalanche",
        "Antfarm (Avalanche)": "antfarm-avalanche",
        "Archly (Avalanche)": "archly-avalanche",
        "Pharaoh Exchange V2": "pharaoh-exchange",
        "Pharaoh Exchange V1": "pharaoh-exchange-v1",
        "Uniswap V2 (Avalanche)": "uniswap-v2-avalanche",
        "VaporDEX V2": "vapordex-v2",
        "Balancer V2 (Avalanche)": "balancer-v2-avalanche",
        "Canary Exchange": "canary-exchange",
        "Uniswap V3 (Avalanche)": "uniswap-v3-avalanche",
        "Flair Dex": "flair-dex",
        "Glacier V2": "glacier",
        HunnySwap: "hunnyswap",
        SoliSnek: "solisnek",
        "Sushiswap V3 (Avalanche)": "sushiswap-v3-avalanche",
        "LFJ V2.1 (Avalanche)": "traderjoe-v2-1-avalanche",
        "Curve (Avalanche)": "curve_avalanche",
        "Kyberswap Classic (Avalanche)": "kyberswap_classic_avalanche",
        onAVAX: "onavax",
        "LFJ V2 (Avalanche)": "traderjoe-v2-avalanche",
        VaporDex: "vapordex",
        Baguette: "baguette",
        "Fraxswap (Avalanche)": "fraxswap_avalanche",
        "Kyberswap Elastic (Avalanche)": "kyberswap_elastic_avalanche",
        "Soulswap (Avalanche)": "soulswap_avalanche",
        "Spice Trade (Avalanche)": "spice_trade_avalanche",
        Swapsicle: "swapsicle",
        Apexswap: "apexswap",
        HurricaneSwap: "hurricaneswap",
        "RadioShack (Avalanche)": "radioshack_avalanche",
        "Elk Finance (Avalanche)": "elk_finance_avax",
    },

    [NetworkType.Fantom]: {
        "Sushiswap (Fantom)": "sushiswap_fantom",
        "Degen Express": "degen-express",
        "Lif3 V3 (Fantom)": "lif3-v3-fantom",
        "Memebox (Fantom)": "memebox-fantom",
        "Orion (Fantom)": "orion-fantom",
        "PyreSwap (Fantom)": "pyreswap-fantom",
        "Skeleton Finance": "skeleton-finance",
        "Solidly V3 (Fantom)": "solidly-v3-fantom",
        "SpookySwap V3": "spookyswap-v3",
        "Archly (FTM)": "archly-ftm",
        Metropolis: "metropolis",
        Redemption: "redemption",
        SkullSwap: "skullswap",
        "Sushiswap V3 (Fantom)": "sushiswap-v3-fantom",
        "Velocimeter (Fantom)": "velocimeter-fantom",
        "WAGMI (Fantom)": "wagmi-fantom",
        "Beethoven X (Fantom)": "beethoven_x_fantom",
        Equalizer: "equalizer",
        "Kyberswap Classic (Fantom)": "kyberswap_classic_fantom",
        MagikSwap: "magikswap",
        "Curve (Fantom)": "curve_ftm",
        "Fraxswap (Fantom)": "fraxswap_fantom",
        "Kyberswap Elastic (Fantom)": "kyberswap_elastic_fantom",
        "RadioShack (Fantom)": "radioshack_fantom",
        "SpiritSwap V2": "spiritswap_v2",
        DarkKnight: "darkknight",
        Excalibur: "excalibur",
        "HyperJump (Fantom)": "hyperjump_ftm",
        ProtoFi: "protofi",
        "Solidly (Fantom)": "solidly",
        WingSwap: "wingswap",
        "Fbomb Finance": "fbomb_finance",
        PaintSwap: "paintswap",
        "Tomb Swap (Fantom)": "tomb_swap_fantom",
        WigoSwap: "wigoswap",
        "Yoshi.exchange (Fantom)": "yoshi_exchange_ftm",
        "Dfyn (Fantom)": "dfyn_fantom",
        "Elk Finance (Fantom)": "elk_finance_ftm",
        "Firebird (Fantom)": "firebird_fantom",
        "Jetswap (Fantom)": "jetswap_fantom",
        "Morpheus Swap": "morpheus_swap",
        SoulSwap: "soulswap",
        SpiritSwap: "spiritswap",
        SpookySwap: "spookyswap",
    },

    [NetworkType.Linea]: {
        "SyncSwap (Linea)": "syncswap-linea",
        "DackieSwap V2 (Linea)": "dackieswap-v2-linea",
        "DackieSwap V3 (Linea)": "dackieswap-v3-linea",
        Etherex: "etherex",
        "Etherex Legacy": "etherex-legacy",
        "Oku Trade (Linea)": "oku-trade-linea",
        "SushiSwap V2 (Linea)": "sushiswap-v2-linea",
        "SyncSwap V2.1 (Linea)": "syncswap-v2-1-linea",
        "Line Hub V2": "line-hub-v2",
        "Line Hub V3": "line-hub-v3",
        "Lynex V2 (Linea)": "lynex-v2-linea",
        "NILE V1": "nile-v1",
        "Chimp Exchange": "chimp-exchange",
        NILE: "nile",
        "Satori (Linea)": "satori-linea",
        "Secta Finance V2": "secta-finance-v2",
        "Secta Finance V3": "secta-finance-v3",
        "Velocore V2 (Linea)": "velocore-v2-linea",
        "Lynex (Linea)": "lynex-linea",
        "Metavault V2 (Linea)": "metavault-v2-linea",
        "Metavault V3 (Linea)": "metavault-v3-linea",
        "PixelSwap (Linea)": "pixelswap-linea",
        "Sushiswap V3 (Linea)": "sushiswap-v3-linea",
        EchoDEX: "echodex",
        "iZiSwap (Linea)": "iziswap-linea",
        "Kyberswap Elastic (Linea)": "kyberswap-elastic-linea",
        "Leetswap (Linea)": "leetswap-linea",
        "Pancakeswap V2 (Linea)": "pancakeswap-v2-linea",
        "Pancakeswap V3 (Linea)": "pancakeswap-v3-linea",
        "Pheasantswap (Linea)": "pheasantswap-linea",
        HorizonDEX: "horizondex",
    },

    [NetworkType.Cronos]: {
        VVS: "vvs",
        "Ebisu's Bay": "ebisus-bay",
        "Obsidian Finance": "obsidian-finance",
        "Solidex V3": "solidex-v3",
        AlienDEX: "aliendex",
        "Archly (Cronos)": "archly-cronos",
        "Candycity Finance": "candycity_finance",
        CroSwap: "croswap",
        "MM Finance V3 (Cronos)": "mm-finance-v3-cronos",
        "Phenix Finance (Cronos)": "phenix-finance-cronos",
        "VVS V3": "vvs-v3",
        "Annex Finance": "annex_finance",
        "Cougar Exchange": "cougar_exchange",
        KryptoDEX: "kryptodex",
        "Kyberswap Elastic (Cronos)": "kyberswap_elastic_cronos",
        "RadioShack (Cronos)": "radioshack_cronos",
        CrowFi: "crowfi",
        CyborgSwap: "cyborgswap",
        DuckyDeFi: "duckydefi",
        "EmpireDEX (Cronos)": "empiredex_cronos",
        PhotonSwap: "photonswap",
        "Firebird (Cronos)": "firebird_cronos",
        "MM Finance": "mm_finance",
        Crodex: "crodex",
        CronaSwap: "cronaswap",
        "Elk Finance": "elk_finance",
    },

    [NetworkType["Gnosis XDAI"]]: {
        Honeyswap: "honeyswap",
        "Sushiswap (Xdai)": "sushiswap_xdai",
        "Elk Finance (Xdai)": "elk_finance_xdai",
        "Swapr (Xdai)": "swapr_xdai",
        "Bao Finance": "bao_finance",
        Levinswap: "levinswap_xdai",
        "Balancer V2 (Gnosis)": "balancer-gnosis",
        "SushiSwap V3 (Gnosis)": "sushiswap-v3-gnosis",
        "Curve (Gnosis)": "curve-gnosis",
        "Oku Trade (Gnosis)": "oku-trade-gnosis",
        "Balancer V3 (Gnosis)": "balancer-v3-gnosis",
    },

    [NetworkType.Tron]: {
        "Sunswap V2": "sunswap-v2",
        "Sunswap V3": "sunswap-v3",
        "JustMoney (Tron)": "justmoney-tron",
        "SushiSwap V2 (Tron)": "sushiswap-v2-tron",
    },

    [NetworkType["Kucoin Community Chain"]]: {
        Kuswap: "kuswap",
        MojitoSwap: "mojitoswap",
        "Elk Finance (KCC)": "elk_finance_kcc",
    },

    [NetworkType.Blast]: {
        "IceCreamSwap (Blast)": "icecreamswap-blast",
        "Ring Protocol (Blast)": "ring-exchange-blast",
        "Thruster V2 (0.3% Fee Tier)": "thruster-v2-0-3-fee-tier",
        "Thruster V2 (1.0% Fee Tier)": "thruster-v2-1-0-fee-tier",
        "MonoSwap V2 (Blast)": "monoswap-V2-blast",
        "DYORSwap (Blast)": "dyorswap-blast",
        BlastDex: "blastdex",
        "Akita Ken": "akita-ken",
        HyperBlast: "hyperblast",
        "BladeSwap (Deprecated soon)": "bladeswap-deprecated",
        "MonoSwap V3 (Blast)": "monoswap-v3-blast",
        "Thruster V3": "thruster-v3",
        "Cyberblast V2": "cyberblast-v2",
        "Cyberblast V3": "cyberblast-v3",
        SwapBlast: "swapblast",
        "BlazeSwap (Blast)": "blazeswap-blast",
        Polia: "polia",
        BegSwap: "begswap",
        Blasterswap: "blasterswap",
        "RogueX Protocol": "roguex-protocol",
        GhostEx: "ghostex",
        "DackieSwap V2 (Blast)": "dackieswap-v2-blast",
        "DackieSwap V3 (Blast)": "dackieswap-v3-blast",
        "Rawr Trade": "rawr-trade",
        Bitdex: "bitdex",
        XDX: "xdx",
        BlasterDEX: "blasterdex",
        "Archly (Blast)": "archly-blast",
        "Uniswap V2 (Blast)": "uniswap-v2-blast",
        "Uniswap V3 (Blast)": "uniswap-v3-blast",
        BladeSwap: "bladeswap",
        "Fenix Finance": "fenix-finance",
        "Blasterswap V3": "blasterswap-v3",
        "SushiSwap V2 (Blast)": "sushiswap-v2-blast",
        "SushiSwap V3 (Blast)": "sushiswap-v3-blast",
        "SquadSwap (Blast)": "squadswap-blast",
        "SquadSwap V3 (Blast)": "squadswap-v3-blast",
        "Uniswap V4 (Blast)": "uniswap-v4-blast",
    },

    [NetworkType.Scroll]: {
        ScrollSwap: "scrollswap",
        PunkSwap: "punkswap",
        "LeetSwap (Scroll)": "leetswap-scroll",
        "SpaceFi (Scroll)": "spacefi-scroll",
        "iZiSwap (Scroll)": "iziswap-scroll",
        Sanctuary: "sanctuary",
        QuillSwap: "quillswap",
        "Icecreamswap (Scroll)": "icecreamswap-scroll",
        Skydrome: "skydrome",
        "Kyberswap Elastic (Scroll)": "kyberswap-elastic-scroll",
        "SyncSwap (Scroll)": "syncswap-scroll",
        "Papyrus Swap": "papyrus-swap",
        CattieSwap: "cattieswap",
        "LuigiSwap (Scroll)": "luigiswap-scroll",
        "Metavault V2 (Scroll)": "metavault-v2-scroll",
        "Metavault V3 (Scroll)": "metavault-v3-scroll",
        "Coffee Dex": "coffee-dex",
        ZadaFinance: "zadafinance",
        "Zebra (Scroll)": "zebra-scroll",
        "Zebra V2 (Scroll)": "zebra-v2-scroll",
        "SushiSwap V3 (Scroll)": "sushiswap-v3-scroll",
        "Z Protocol": "z-protocol",
        "Oku Trade (Scroll)": "oku-trade-scroll",
        "Skydrome V2": "skydrome-v2",
        "Tokan Exchange": "tokan-exchange",
        "Nuri V2": "nuri-v2",
        "SushiSwap V2 (Scroll)": "sushiswap-v2-scroll",
        "SyncSwap V2.1 (Scroll)": "syncswap-v2-1-scroll",
        Scribe: "scribe",
        "Nuri (Legacy)": "nuri-legacy",
        "Maverick V2 (Scroll)": "maverick-v2-scroll",
        "Honeypop DEX": "honeypop-dex",
    },

    [NetworkType["Manta Pacific"]]: {
        "LeetSwap (Manta)": "leetswap-manta",
        MantaSwap: "mantaswap",
        ApertureSwap: "apertureswap",
        "iZiSwap (Manta Pacific)": "iziswap-manta-pacific",
        PacificSwap: "pacificswap",
        "Quickswap V3 (Manta Pacific)": "quickswap-v3-manta-pacific",
        "Cetoswap (Manta Pacific)": "cetoswap",
        Firefly: "firefly",
        "Gull Network": "gull-network",
        "Oku Trade (Manta Pacific)": "oku-trade-manta-pacific",
    },

    [NetworkType["Merlin Chain"]]: {
        MerlinSwap: "merlinswap",
        "DYORSwap (Merlin)": "dyorswap-merlin",
        BitGenie: "bitgenie-merlin-chain",

    },

    [NetworkType.Bitlayer]: {
        "Macaron (Bitlayer)": "macaron-bitlayer",
        "BubbleSwap (Bitlayer)": "bubbleswap-bitlayer",
        "Macaron StableSwap (Bitlayer)": "macaron-stableswap-bitlayer",
        "iSwap (Bitlayer)": "iswap-bitlayer",
    },

    [NetworkType["zkLink Nova"]]: {
        "iZiSwap (zkLink Nova)": "iziswap-zklink-nova",
        NovaSwap: "novaswap",
        "WAGMI (zkLink Nova)": "wagmi-zklink-nova",
        Linkswap: "linkswap",
    },

    [NetworkType.Gravity]: {
        "Icecreamswap (Gravity Alpha)": "icecreamswap-gravity-alpha",
        "iZiSwap (Gravity Alpha)": "iziswap-gravity-alpha",
        "Camelot V3 (Gravity)": "camelot-v3-gravity",
        "Camelot V2 (Gravity)": "camelot-v2-gravity",
    },

    [NetworkType["Morph L2"]]: {
        "DYORSwap (Morph L2)": "dyorswap-morph-l2",
        "Abstradex (Morph L2)": "abstradex-morph-l2",
        "iZiSwap (Morph L2)": "iziswap-morph-l2",
        MorFi: "morfi",
        "BulbaSwap V2": "bulbaswap-v2",
        "Bulbaswap V3": "bulbaswap-v3",
    },

    [NetworkType.Berachain]: {
        BEX: "bex",
        "Kodiak V2": "kodiak-v2",
        "Kodiak V3": "kodiak-v3",
        "DYORSwap (Berachain)": "dyorswap-berachain",
        "Holdstation (Berachain)": "holdstation-berachain",
        BurrBear: "burrbear",
        Bulla: "bulla",
        "BrownFi (Berachain)": "brownfi-berachain",
        WinnieSwap: "winnieswap",
    },

    [NetworkType.Abstract]: {
        "Uniswap V2 (Abstract)": "uniswap-v2-abstract",
        "Uniswap V3 (Abstract)": "uniswap-v3-abstract",
        "Kona V2": "kona-v2",
        "Aborean Finance V2": "aborean-finance-v2",
        "Aborean Finance V3": "aborean-finance-v3",
    },

    [NetworkType.Hashkey]: {
        HyperIndex: "hyperindex",
    },

    [NetworkType.Sonic]: {
        "DYORSwap (Sonic)": "dyorswap-sonic",
        "Metropolis Simple (Sonic)": "metropolis-sonic",
        "Solidly V3 (Sonic)": "solidly-v3-sonic",
        "Spookyswap V3 (Sonic)": "spookyswap-v3-sonic",
        Memebox: "memebox",
        "Equalizer (Sonic)": "equalizer-sonic",
        "Metropolis DLMM (Sonic)": "metropolis-dlmm-sonic",
        MobiusDEX: "mobiusdex",
        "Sushiswap V3 (Sonic)": "sushiswap-v3-sonic",
        "Sushiswap V2 (Sonic)": "sushiswap-v2-sonic",
        SonicSwap: "sonicswap",
        "Wagmi (Sonic)": "wagmi-sonic",
        "Abstradex (Sonic)": "abstradex-sonic",
        SilverSwap: "silverswap",
        "Sonic Market": "sonic-market",
        "Shadow Exchange": "shadow-exchange",
        "SwapX Algebra": "swapx-algebra",
        "SwapX V2": "swapx-v2",
        "Beets (Sonic)": "beets-sonic",
        "Spookyswap V2 (Sonic)": "spookyswap-v2-sonic",
        DeFive: "defive",
        "Shadow Exchange (Legacy)": "shadow-exchange-legacy",
        "9mm V3 (Sonic)": "9mm-v3-sonic",
        "9mm V2 (Sonic)": "9mm-v2-sonic",
        "Curve (Sonic)": "curve-sonic",
        "KEWLSwap (Sonic)": "kewlswap-sonic",
        SonicxSwap: "sonicxswap",
        "Oku Trade (Sonic)": "oku-trade-sonic",
        "zkSwap Finance V2 (Sonic)": "zkswap-finance-v2-sonic",
        "zkSwap Finance V3 (Sonic)": "zkswap-finance-v3-sonic",
        Atlantis: "atlantis",
        FatfingerSwap: "fatfingerswap",
        "Omni Exchange V2 (Sonic)": "omni-exchange-v2-sonic",
        "Omni Exchange V3 (Sonic)": "omni-exchange-v3-sonic",
        "Omni Exchange V4 (Sonic)": "omni-exchange-v4-sonic",
        "Beets V3 (Sonic)": "beets-v3-sonic",
    },

    [NetworkType.Story]: {
        "PiperX V3": "piperx-v3",
        "Piperx V2": "piperx-v2",
        "Story Hunt": "story-hunt",
    },

    [NetworkType.Unichain]: {
        "Uniswap V2 (Unichain)": "uniswap-v2-unichain",
        "Uniswap V3 (Unichain)": "uniswap-v3-unichain",
        "Uniswap V4 (Unichain)": "uniswap-v4-unichain",
        "Velodrome Finance Slipstream (Unichain)": "velodrome-finance-slipstream-unichain",
        "Velodrome Finance V2 (Unichain)": "velodrome-finance-v2-unichain",
        "Bunni (Unichain)": "bunni-unichain",
    },

    [NetworkType["World Chain"]]: {
        "Uniswap V3 (World Chain)": "uniswap-v3-world-chain",
        "DYORSwap (World Chain)": "dyorswap-world-chain",
        "Multex (World Chain)": "multex-world-chain",
        "Uniswap V2 (World Chain)": "uniswap-v2-world-chain",
        "DackieSwap V2 (World Chain)": "dackieswap-v2-world-chain",
        "DackieSwap V3 (World Chain)": "dackieswap-v3-world-chain",
        RealSwap: "realswap",
        "Uniswap V4 (World Chain)": "uniswap-v4-world-chain",
    },

    [NetworkType.Soneium]: {
        "DYORSwap (Soneium)": "dyorswap-soneium",
        "Kyo Finance V3": "kyo-finance-v3",
        "Kyo Finance V2": "kyo-finance-v2",
        SoneFi: "sonefi",
        "Velodrome Finance Slipstream (Soneium)": "velodrome-finance-slipstream-soneium",
        "Velodrome Finance V2 (Soneium)": "velodrome-finance-v2-soneium",
        Sonex: "sonex",
        "Sonus V3": "sonus-v3",
        "Sonus V2": "sonus-v2",
        "Uniswap V2 (Soneium)": "uniswap-v2-soneium",
        "Uniswap V3 (Soneium)": "uniswap-v3-soneium",
        "Quickswap V4 (Soneium)": "quickswap-v3-soneium",
    },

    [NetworkType["Monad Testnet"]]: {
        "Uniswap V2 (Monad Testnet)": "uniswap-v2-monad-testnet",
        "IziSwap (Monad Testnet)": "iziswap-monad-testnet",
        "Bean Exchange": "bean-exchange",
        "Madness Finance": "madness-finance",
        "zkSwap Finance V2 (Monad Testnet)": "zkswap-finance-v2-monad-testnet",
        "zkSwap Finance V3 (Monad Testnet)": "zkswap-finance-v3-monad-testnet",
        "zkSwap Finance Stable (Monad Testnet)": "zkswap-finance-stable-monad-testnet",
        Purps: "purps",
        OctoSwap: "octoswap",
        "Uniswap V3 (Monad Testnet)": "uniswap-v3-monad-testnet",
        "Monday Trade": "monday-trade",
        "Morpheus (Monad Testnet)": "morpheus-monad-testnet",
        "Madness Finance V2": "madness-finance-v2",
        "OctoSwap CL": "octoswap-v3",
        NeuraDEX: "neuradex",
    },

    [NetworkType.Zircuit]: {

        "DYORSwap (Zircuit)": "dyorswap-zircuit",
        Zuit: "zuit",
        "Ocelex V2": "ocelex-v2",
        "Ocelex V3": "ocelex-v3",
    },

    [NetworkType.Solana]: {
        Raydium: "raydium",
        Orca: "orca",
        "Raydium (CLMM)": "raydium-clmm",
        FluxBeam: "fluxbeam",
        Meteora: "meteora",
        Dexlab: "dexlab",
        "Daos.fun": "daos-fun",
        PumpSwap: "pumpswap",
        "Virtuals (Solana)": "virtuals-solana",
        "Boop.fun": "boop-fun",
        "Saros AMM": "saros-amm",
        "Meteora DBC": "meteora-dbc",
        Byreal: "byreal",
        "Pancakeswap V3 (Solana)": "pancakeswap-v3-solana",
        "Meteora DAMM V2": "meteora-damm-v2",
        "Raydium Launchlab": "raydium-launchlab",
        "Pump.fun": "pump-fun",
        "Saros DLMM": "saros-dlmm",
        Wavebreak: "wavebreak",
        Heaven: "heaven",
        "Token Mill": "token-mill",
        DeFiTuna: "defituna",
        Moonit: "moonit",
    },

    [NetworkType["Sui Network"]]: {
        BlueMove: "bluemove",
        Cetus: "cetus",
        FlameSwap: "flameswap",
        Suiswap: "suiswap",
        KriyaDEX: "kriya-dex",
        "Turbos Finance": "turbos-finance",
        Bluefin: "bluefin",
        FlowX: "flow-x",
        "Magma Finance": "magma-finance",
        "FlowX CLMM": "flowx-clmm",
        Momentum: "momentum",
        STEAMM: "steamm",
        "Full Sail": "fullsail-finance"
    }
} as const satisfies Record<Network, Record<string, string>>;

export type Dex = {
    [N in keyof typeof NETWORK_DEXES]: typeof NETWORK_DEXES[N][keyof typeof NETWORK_DEXES[N]]
}[keyof typeof NETWORK_DEXES];

export type DexLabel = {
    [N in keyof typeof NETWORK_DEXES]: keyof typeof NETWORK_DEXES[N]
}[keyof typeof NETWORK_DEXES];

export const DEX_LABELS = Object.fromEntries(
    Object.entries(NETWORK_DEXES).flatMap(([_, dexes]) => 
        Object.entries(dexes).map(([label, slug]) => [slug, label])
    )
) as Record<Dex, DexLabel>;